### ISSUE TITLE
nav.ejs

### ISSUE THREAD

**Issue by BluAimz** [TheHellTower/Discord-Bot-List#62]
When I put an id of a random member in the route, it returns an error:

19|             </a>
    20|         <% } %>
 >> 21|         <% if ((req.baseUrl == "/user" || req.baseUrl == "/me") && userProfile) { %>
    22|             <a href="/user/<%= userProfile.id %>">
    23|                 <span class="navtext"><%= userProfile.username %></span>
    24|             </a>

userProfile is not defined
    at eval ("C:\\Users\\marti\\Desktop\\Discord-Bot-List-master\\src\\dynamic\\includes\\nav.ejs":33:64)
    at nav (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:703:17)
    at include (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:701:39)
    at eval ("C:\\Users\\marti\\Desktop\\Discord-Bot-List-master\\src\\dynamic\\404.ejs":15:17)
    at 404 (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:703:17)
    at tryHandleCache (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:274:36)
    at exports.renderFile [as engine] (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:491:10)
    at View.render (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\application.js:657:10)
    at Function.render (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\application.js:609:3)

**Comment by TheHellTower** [comment]
> When I put an id of a random member in the route, it returns an error:

Hey, I finish something then I look at it !

**Comment by BluAimz** [comment]
> > When I put an id of a random member in the route, it returns an error:
> 
> Hey, I finish something then I look at it !

Okay!

**Comment by TheHellTower** [comment]
Found the issue ! Fixed !
